import:
    - source: .travis.integration.yml
      if: 1 + 1 = 2
    # blocking as could not find a way to set the environment variable before selecting the config file
    # - source: .travis.deployment.yml
    #  if: branch = master AND env(READY_TO_DEPLOY) = yes
