language: node_js
node_js:
    - 14.15.4
before_install:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
install:
    - npm install
scripts:
    # Prettier
    - npm run format:check
    # ESLint
    - npm run lint:check
    # Docker container
    - docker-compose up -d
    # Automated Test
    - npm run test
    # Build
    - npm run build
after_script:
    - docker-compose stop && docker-compose rm -f && docker-compose down --volumes
