language: node_js
node_js:
    - 14.15.4
install:
    - npm install
script:
    - npm run build
    - npm run start:prod
deploy:
    provider: elasticbeanstalk
    region: 'ap-south-1'
    app: 'IELTS back-end'
    env: 'Ieltsbackend-env'
    bucket_name: $ELASSTIC_BEANSTALK_S3_BUCKET
    bucket_path: 'IELTS back-end'
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    on:
        branch: master
