version: '3.7'
services:
    ielts-gibberish-database:
        image: postgres:11
        container_name: ielts-gibberish-postgres
        restart: always
        ports:
            - '5431:5432'
        environment:
            POSTGRES_PASSWORD: 123
            POSTGRES_USER: postgres
            POSTGRES_DB: ielts-gibberish
        volumes:
            - ielts-gibberish-postgres-data:/var/lib/postgresql/data
volumes:
    ielts-gibberish-postgres-data:
        driver: local
